' vivaldi parametrica
' versione 2.0

Sub Main ()
'@ EXECUTE MACRO: 2_0VIVALDI
ON ERROR GOTO PROSEGUI
COMPONENT.DELETE "COMPONENT1"
COMPONENT.DELETE "COMPONENT2"
COMPONENT.DELETE "COMPONENT3"
PROSEGUI: ON ERROR GOTO 0

IF (GETNUMBEROFPARAMETERS=0) THEN 'INIZIALIZZO I PARAMETRI
BEGIN DIALOG USERDIALOG 470,287,"VIVALDI" ' %GRID:10,7,1,1
GROUPBOX 20,0,430,147,"PARAMETRI SLOTLINE - UNITÀ MM",.GROUPBOX1
TEXT 30,21,180,14,"LUNGHEZZA ANTENNA",.TEXT1
TEXT 30,63,180,14,"LARGHEZZA PROFILO DI INGRESSO",.TEXT2
TEXT 30,42,180,14,"LARGHEZZA PROFILO DI USCITA",.TEXT3
TEXT 30,84,170,14,"CURVATURA PROFILO" ,.TEXT4
TEXT 30,105,160,14,"CENTRO CAVITÀ",.TEXT5
TEXT 30,126,130,14,"RAGGIO CAVITÀ",.TEXT6
GROUPBOX 20,161,430,77,"PARAMETRI MICROSTRISCIA E STUB - UNITÀ MM",.GROUPBOX2
TEXT 30,175,160,14,"LARGHEZZA MICROSTRISCIA",.TEXT7
TEXT 30,196,170,14,"X STUB" ,.TEXT8
TEXT 30,217,100,14,"Y STUB",.TEXT9
OKBUTTON 160,259,120,21
TEXTBOX 240,21,120,15,.X11
TEXTBOX 240,42,120,15,.Y11
TEXTBOX 240,63,120,15,.Y00
TEXTBOX 240,84,120,15,.AAA
TEXTBOX 240,105,120,15,.ALFA
TEXTBOX 240,126,120,15,.BBB
TEXTBOX 240,175,120,15,.WIDTH
TEXTBOX 240,196,120,15,.XSTUB4
TEXTBOX 240,217,120,15,.YSTUB
END DIALOG

DIM DLG AS USERDIALOG
DLG.X11="35"
DLG.Y00="0.25" 'LARGHEZZA BOCCA
DLG.Y11="15"
DLG.ALFA="15" 'CENTRO
DLG.AAA="0.4"
DLG.BBB="2" 'RAGGIO CIRCONFERENZA
DLG.WIDTH="1.12"
DLG.XSTUB4="25"
DLG.YSTUB="4"
DIALOG DLG
STOREDOUBLEPARAMETER("X11" , 0)
STOREDOUBLEPARAMETER("Y00" , 0)
STOREDOUBLEPARAMETER("Y11" , 0)
STOREDOUBLEPARAMETER("ALFA", 0)
STOREDOUBLEPARAMETER("AAA" , 0)
STOREDOUBLEPARAMETER("BBB", 0)
STOREDOUBLEPARAMETER("WIDTH" , 0)
STOREDOUBLEPARAMETER("XSTUB4" , 0)
STOREDOUBLEPARAMETER("YSTUB", 0)
STOREPARAMETER("XSTUB5", 0)
END IF

DIM XXX AS DOUBLE , YYY AS DOUBLE , BBB AS DOUBLE
DIM X00 AS DOUBLE, X11 AS DOUBLE, Y11 AS DOUBLE, Y00 AS DOUBLE, ALFA AS DOUBLE, CRL AS DOUBLE
DIM AAA AS DOUBLE, TH2 AS DOUBLE, TH AS DOUBLE
DIM WIDTH AS DOUBLE, YSTUB AS DOUBLE ,RSTUB AS DOUBLE,XSTUB4 AS DOUBLE ,XSTUB5 AS DOUBLE,LSTUB AS DOUBLE

IF (RESTOREPARAMETER("X11" )=0) THEN
X11 = EVALUATE(DLG.X11)
Y00=EVALUATE(DLG.Y00)/2 'LARGHEZZA BOCCA
Y11=EVALUATE(DLG.Y11)/2
ALFA=EVALUATE(DLG.ALFA)+0.1 'CENTRO
AAA=EVALUATE(DLG.AAA)
BBB=EVALUATE(DLG.BBB) 'RAGGIO CIRCONFERENZA
WIDTH=EVALUATE(DLG.WIDTH)
XSTUB4=EVALUATE(DLG.XSTUB4)
YSTUB=EVALUATE(DLG.YSTUB)
X00=X11/2 'INIZIO BOCCA
STOREDOUBLEPARAMETER("X00" ,X00)
SETPARAMETERDESCRIPTION ("X00" , "INIZIO BOCCA" )
STOREDOUBLEPARAMETER("X11" ,X11)
SETPARAMETERDESCRIPTION ("X11" , "LUNGHEZZA ANTENNA" )
STOREDOUBLEPARAMETER("Y00" ,Y00)
SETPARAMETERDESCRIPTION ("Y00" , "LARGHEZZA PROFILO INGRESSO" )
STOREDOUBLEPARAMETER("Y11" ,Y11)
SETPARAMETERDESCRIPTION ("Y11" , "LARGHEZZA PROFILO USCITA" )
STOREDOUBLEPARAMETER("ALFA",ALFA)
SETPARAMETERDESCRIPTION ("ALFA", "CENTRO CAVITÀ" )
STOREDOUBLEPARAMETER("AAA" ,AAA)
SETPARAMETERDESCRIPTION ("AAA", "CURVATURA PROFILO" )
STOREDOUBLEPARAMETER("BBB",BBB)
SETPARAMETERDESCRIPTION ("BBB" , "RAGGIO CAVITÀ" )
STOREDOUBLEPARAMETER("WIDTH" ,WIDTH)
SETPARAMETERDESCRIPTION ("WIDTH", "LARGHEZZA MICROSTRISCIA" )
STOREDOUBLEPARAMETER("XSTUB4" ,XSTUB4)
SETPARAMETERDESCRIPTION ("XSTUB4" , "X STUB" )
STOREDOUBLEPARAMETER("YSTUB",YSTUB)
SETPARAMETERDESCRIPTION ("YSTUB", "Y STUB" )
STOREDOUBLEPARAMETER("XSTUB5" ,X00)
END IF

X11 = RESTOREDOUBLEPARAMETER("X11" )
Y00 = RESTOREDOUBLEPARAMETER("Y00" )
X00 = RESTOREDOUBLEPARAMETER("X00" )
Y11 = RESTOREDOUBLEPARAMETER("Y11" )
ALFA = RESTOREDOUBLEPARAMETER("ALFA" )
AAA = RESTOREDOUBLEPARAMETER("AAA")
BBB= RESTOREDOUBLEPARAMETER("BBB")
CRL=ALFA-BBB
WIDTH = RESTOREDOUBLEPARAMETER("WIDTH")
XSTUB4 = RESTOREDOUBLEPARAMETER("XSTUB4" )
YSTUB = RESTOREDOUBLEPARAMETER("YSTUB")
'SETPARAMETERDESCRIPTION ("Y00", "LUNGHEZZA ANTENNA" )
CURVE.NEWCURVE "2D-ANALYTICAL"
'MSGBOX("MACRO VIVALDI REV. 1.0" ,0)
DIM SCURVENAME AS STRING

WITH UNITS
.GEOMETRY "MM"
.FREQUENCY "GHZ"
.TIME "NS"
.TEMPERATUREUNIT "CELSIUS"
.VOLTAGE "V"
.CURRENT "A"
.RESISTANCE "OHM"
.CONDUCTANCE "S"
.CAPACITANCE "PF"
.INDUCTANCE "NH"
END WITH

SCURVENAME = "VIVALDI" 

WITH POLYGON
.RESET
.NAME "REGIONELINEARE1"
.CURVE "2D-ANALYTICAL"
.POINT X00, Y00
.LINETO X00+3.5, Y00
YYY = Y00+((Y11-Y00)/(EXP(AAA*X11+X00)-1))*(EXP(AAA*(X00+3.5)+X00)-1)
.LINETO X00+3.5,YYY
.CREATE
END WITH

WITH POLYGON
.RESET
.NAME "REGIONELINEARE2"
.CURVE "2D-ANALYTICAL"
.POINT X00, -Y00
.LINETO X00+3.5, -Y00
YYY=-Y00-((Y11-Y00)/(EXP(AAA*X11+X00)-1))*(EXP(AAA*(X00+3.5)+X00)-1)
.LINETO X00+3.5,YYY
.CREATE
END WITH

WITH POLYGON
.RESET
.NAME "REGIONELINEARE3"
.CURVE "2D-ANALYTICAL"
.POINT X11, Y11
.LINETO 0, Y11
.LINETO 0, -Y11
.LINETO X11, -Y11
.CREATE
END WITH

WITH SPLINE
.RESET
.NAME "EXP_POSITIVO"
.CURVE "2D-ANALYTICAL"
FOR XXX = X00+3.5 TO X11-1 STEP 0.5
YYY = Y00+((Y11-Y00)/(EXP(AAA*X11+X00)-1))*(EXP(AAA*XXX+X00)-1) 
.LINETO XXX , YYY
NEXT XXX
.LINETO X11,Y11
.CREATE
END WITH

WITH SPLINE
.RESET
.NAME "EXP_NEGATIVO"
.CURVE "2D-ANALYTICAL"
FOR XXX=X00+3.5 TO X11-1 STEP 0.5
YYY=-Y00-((Y11-Y00)/(EXP(AAA*X11+X00)-1))*(EXP(AAA*XXX+X00)-1)
.LINETO XXX,YYY
NEXT XXX
.LINETO X11,-Y11
.CREATE
END WITH

WITH ARC
.RESET
.NAME "ARCO"
.CURVE "2D-ANALYTICAL"
.ORIENTATION "COUNTERCLOCKWISE"
.XCENTER X00-BBB
.YCENTER 0
.X1 X00
.Y1 Y00
.X2 X00
.Y2 -Y00
.SEGMENTS "0"
.CREATE
END WITH

WITH MATERIAL
.RESET
.NAME "ALUMINA (99.5%) (LOSS FREE)"
.FRQTYPE "ALL"
.TYPE "NORMAL"
.EPSILON "9.9"
.MUE "1.0"
.KAPPA "0.0"
.TAND "0.0"
.TANDFREQ "0.0"
.TANDGIVEN "FALSE"
.TANDMODEL "CONSTTAND"
.KAPPAM "0.0"
.TANDM "0.0"
.TANDMFREQ "0.0"
.TANDMGIVEN "FALSE"
.TANDMMODEL "CONSTKAPPA"
.DISPMODELEPS "NONE"
.DISPMODELMUE "NONE"
.DISPERSIVEFITTINGSCHEMEEPS "GENERAL 1ST"
.DISPERSIVEFITTINGSCHEMEMUE "GENERAL 1ST"
.USEGENERALDISPERSIONEPS "FALSE"
.USEGENERALDISPERSIONMUE "FALSE"
.RHO "0.0"
.THERMALTYPE "NORMAL"
.THERMALCONDUCTIVITY "0"
.COLOUR "0.75" , "0.95", "0.85"
.WIREFRAME "FALSE"
.TRANSPARENCY "0"
.CREATE
END WITH

WITH MATERIAL
.RESET
.NAME "COPPER"
.FRQTYPE "HF"
.TYPE "LOSSY METAL"
.MUE "1.0"
.KAPPA "5.8E+007"
.FRQTYPE "ALL"
.TYPE "LOSSY METAL"
.MUE "1.0"
.KAPPA "5.8E+007"
.RHO "0.0"
.THERMALTYPE "NORMAL"
.THERMALCONDUCTIVITY "401.0"
.FRQTYPE "STATIC"
.TYPE "NORMAL"
.EPSILON "1"
.MUE "1.0"
.KAPPA "5.8E+007"
.TAND "0.0"
.TANDFREQ "0.0"
.TANDGIVEN "FALSE"
.TANDMODEL "CONSTTAND"
.KAPPAM "0"
.TANDM "0.0"
.TANDMFREQ "0.0"
.TANDMGIVEN "FALSE"
.TANDMMODEL "CONSTTAND"
.DISPMODELEPS "NONE"
.DISPMODELMUE "NONE"
.DISPERSIVEFITTINGSCHEMEEPS "GENERAL 1ST"
.DISPERSIVEFITTINGSCHEMEMUE "GENERAL 1ST"
.USEGENERALDISPERSIONEPS "FALSE"
.USEGENERALDISPERSIONMUE "FALSE"
.COLOUR "1" , "1", "0"
.WIREFRAME "FALSE"
.REFLECTION "FALSE"
.ALLOWOUTLINE "TRUE"
.TRANSPARENTOUTLINE "FALSE"
.TRANSPARENCY "0"
.CREATE
END WITH

COMPONENT.NEW "COMPONENT1"

WITH EXTRUDECURVE
.RESET
.NAME "VIVALDI_SOLID"
.COMPONENT "COMPONENT1"
.MATERIAL "COPPER"
.THICKNESS "0.035"
.TWISTANGLE "0.0"
.TAPERANGLE "0.0"
.CURVE "2D-ANALYTICAL"
.CREATE
END WITH

WITH MATERIAL
.RESET
.NAME "ROGERS RO4003 (LOSS FREE)"
.FRQTYPE "ALL"
.TYPE "NORMAL"
.EPSILON "3.38"
.MUE "1.0"
.KAPPA "0.0"
.TAND "0.0"
.TANDFREQ "0.0"
.TANDGIVEN "FALSE"
.TANDMODEL "CONSTTAND"
.KAPPAM "0.0"
.TANDM "0.0"
.TANDMFREQ "0.0"
.TANDMGIVEN "FALSE"
.TANDMMODEL "CONSTKAPPA"
.DISPMODELEPS "NONE"
.DISPMODELMUE "NONE"
.DISPERSIVEFITTINGSCHEMEEPS "GENERAL 1ST"
.DISPERSIVEFITTINGSCHEMEMUE "GENERAL 1ST"
.USEGENERALDISPERSIONEPS "FALSE"
.USEGENERALDISPERSIONMUE "FALSE"
.RHO "0.0"
.THERMALTYPE "NORMAL"
.THERMALCONDUCTIVITY "0.64"
.SETACTIVEMATERIAL "ALL"
.COLOUR "0.75" , "0.95", "0.85"
.WIREFRAME "FALSE"
.TRANSPARENCY "0"
.CREATE
END WITH

COMPONENT.NEW "COMPONENT2"

WITH BRICK
.RESET
.NAME "SUBSTRATO"
.COMPONENT "COMPONENT2"
.MATERIAL "ROGERS RO4003 (LOSS FREE)"
.XRANGE "0", X11
.YRANGE -Y11, Y11
.ZRANGE "-0.508", "0.000000"
.CREATE
END WITH

XSTUB5=RESTOREDOUBLEPARAMETER("XSTUB5")

WITH POLYGON
.RESET
.NAME "STRIPLINE1"
.CURVE "STRIPLINE"
'.POINT "0" , -Y11/2
'.LINETO X00+1+WIDTH , -Y11/2
'.LINETO X00+1+WIDTH, Y00
.POINT X00+0.5 , -Y11
.LINETO X00+0.5+WIDTH, -Y11
.LINETO X00+0.5+WIDTH, 0
YYY = SQR((YSTUB-0)^2)
.LINETO XSTUB4,YYY
.CREATE
END WITH

WITH SPLINE
.RESET
.NAME "ARCO"
.CURVE "STRIPLINE"
.POINT XSTUB4, YYY
FOR XXX = XSTUB4-0.5 TO XSTUB5 STEP -0.5
YYY = SQR((XSTUB4-X00-0.5-WIDTH/2)^2+(YSTUB)^2-(XXX-X00-0.5-WIDTH/2)^2)
.LINETO XXX , YYY
NEXT XXX
.CREATE
END WITH

WITH POLYGON
.RESET
.NAME "STRIPLINE2"
.CURVE "STRIPLINE"
.POINT XXX+0.5 , YYY
.LINETO X00+0.5, 0
.LINETO X00+0.5 , -Y11
.CREATE
END WITH

WITH EXTRUDECURVE
.RESET
.NAME "STRIPLINE"
.COMPONENT "COMPONENT3"
.MATERIAL "COPPER"
.THICKNESS "-0.035"
.TWISTANGLE "0.0"
.TAPERANGLE "0.0"
.CURVE "STRIPLINE:STRIPLINE2"
.CREATE
END WITH

WITH TRANSFORM
.RESET
.NAME "COMPONENT3"
.VECTOR "0" , "0", " -0.508"
.USEPICKEDPOINTS "FALSE"
.INVERTPICKEDPOINTS "FALSE"
.MULTIPLEOBJECTS "FALSE"
.GROUPOBJECTS "FALSE"
.REPETITIONS "1"
.MULTIPLESELECTION "FALSE"
.TRANSLATEADVANCED
END WITH

WITH BACKGROUND
.RESET
.TYPE "NORMAL"
.EPSILON "1.0"
.MUE "1.0"
.THERMALTYPE "NORMAL"
.THERMALCONDUCTIVITY "0.0"
.XMINSPACE "0.0"
.XMAXSPACE "0.0"
.YMINSPACE "0.0"
.YMAXSPACE "0.0"
.ZMINSPACE "0.0"
.ZMAXSPACE "0.0"
.APPLYINALLDIRECTIONS "FALSE"
END WITH

SOLVER.FREQUENCYRANGE "0.0" , "11"

WITH BOUNDARY
.XMIN "EXPANDED OPEN"
.XMAX "EXPANDED OPEN"
.YMIN "EXPANDED OPEN"
.YMAX "EXPANDED OPEN"
.ZMIN "EXPANDED OPEN"
.ZMAX "EXPANDED OPEN"
.XSYMMETRY "NONE"
.YSYMMETRY "NONE"
.ZSYMMETRY "NONE"
.XMINTHERMAL "ISOTHERMAL"
.XMAXTHERMAL "ISOTHERMAL"
.YMINTHERMAL "ISOTHERMAL"
.YMAXTHERMAL "ISOTHERMAL"
.ZMINTHERMAL "ISOTHERMAL"
.ZMAXTHERMAL "ISOTHERMAL"
.XSYMMETRYTHERMAL "NONE"
.YSYMMETRYTHERMAL "NONE"
.ZSYMMETRYTHERMAL "NONE"
.APPLYINALLDIRECTIONS "TRUE"
.XMINTEMPERATURE ""
.XMINTEMPERATURETYPE "NONE"
.XMAXTEMPERATURE ""
.XMAXTEMPERATURETYPE "NONE"
.YMINTEMPERATURE ""
.YMINTEMPERATURETYPE "NONE"
.YMAXTEMPERATURE ""
.YMAXTEMPERATURETYPE "NONE"
.ZMINTEMPERATURE ""
.ZMINTEMPERATURETYPE "NONE"
.ZMAXTEMPERATURE ""
.ZMAXTEMPERATURETYPE "NONE"
END WITH

WITH MESH
.AUTOMESHSTRAIGHTLINES "TRUE"
.AUTOMESHELLIPTICALLINES "TRUE"
.AUTOMESHREFINEATPECLINES "FALSE", "2"
.AUTOMESHREFINEPECALONGAXESONLY "FALSE"
.AUTOMESHATELLIPSEBOUNDS "TRUE" , "10"
.AUTOMESHATWIREENDPOINTS "TRUE"
.AUTOMESHATPROBEPOINTS "TRUE"
.SETAUTOMESHREFINEDIELECTRICSTY PE "GENERALIZED"
.MERGETHINPECLAYERFIXPOINTS "FALSE"
.EQUILIBRATEMESH "TRUE"
.EQUILIBRATEMESHRATIO "1.19"
.USECELLASPECTRATIO "FALSE"
.CELLASPECTRATIO "50.0"
.USEPECEDGEMODEL "TRUE"
.MESHTYPE "PBA"
.AUTOMESHLIMITSHAPEFACES "TRUE"
.AUTOMESHNUMBEROFSHAPEFACES "1000"
.POINTACCENHANCEMENT "0"
.SURFACEOPTIMIZATION "TRUE"
.SURFACESMOOTHING "3"
.MINIMUMCURVATUREREFINEMENT "100"
.CURVATUREREFINEMENTFACTOR "0.05"
.SMALLFEATURESIZE "0.0"
.SURFACETOLERANCE "0.0"
.SURFACETOLERANCETYPE "RELATIVE"
.NORMALTOLERANCE "22.5"
.SURFACEMESHENRICHMENT "0"
.VOLUMEOPTIMIZATION "TRUE"
.VOLUMESMOOTHING "TRUE"
.VOLUMEMESHMETHOD "DELAUNAY"
.SURFACEMESHMETHOD "GENERAL"
.DELAUNAYOPTIMIZATIONLEVEL "2"
.DELAUNAYPROPAGATIONFACTOR "1.050000"
.DENSITYTRANSITIONS "0.5"
.MESHALLREGIONS "FALSE"
.CONVERTGEOMETRYDATAAFTERMESHING "TRUE"
.AUTOMESHFIXPOINTSFORBACKGROUND "TRUE"
.PBATYPE "PBA"
.AUTOMATICPBATYPE "FALSE"
.FPBAAVOIDNONREGUNITE "TRUE"
.DETECTSMALLSOLIDPEC "FALSE"
.CONSIDERSPACEFORLOWERMESHLIMIT "TRUE"
.RATIOLIMITGOVERNSLOCALREFINEMENT "FALSE"
.FASTPBAGAPDETECTION "FALSE"
.FPBAGAPTOLERANCE "0.001"
.SETMAXPARALLELTHREADS "8"
.SETPARALLELMODE "MAXIMUM"
END WITH

WITH SOLVER
.USESPLITCOMPONENTS "TRUE"
.PBAFILLLIMIT "99"
.ENABLESUBGRIDDING "FALSE"
.ALWAYSEXCLUDEPEC "FALSE"
END WITH

PICK.PICKMIDPOINTFROMID "COMPONENT3:STRIPLINE", "5"
PICK.MOVEPOINT "-1" , "0.0", "0.0", "0.575", "TRUE"

WITH DISCRETEPORT
.RESET
.PORTNUMBER "2"
.TYPE "SPARAMETER"
.IMPEDANCE "50.0"
.VOLTAGE "1.0"
.CURRENT "1.0"
.USEPICKEDPOINTS "TRUE"
.LOCALCOORDINATES "FALSE"
.MONITOR "FALSE"
.CREATE
END WITH
MESH.SETCREATOR "HIGH FREQUENCY"
END SUB
